export const POKE_LOCAL_IMGS: Record<string, any> = {
  bulbasaur: require("../../assets/img/pokemons/bulbasaur.png"),
  ivysaur: require("../../assets/img/pokemons/ivysaur.png"),
  venusaur: require("../../assets/img/pokemons/venusaur.png"),
  charmander: require("../../assets/img/pokemons/charmander.png"),
  charmeleon: require("../../assets/img/pokemons/charmeleon.png"),
  charizard: require("../../assets/img/pokemons/charizard.png"),
  squirtle: require("../../assets/img/pokemons/squirtle.png"),
  wartortle: require("../../assets/img/pokemons/wartortle.png"),
  blastoise: require("../../assets/img/pokemons/blastoise.png"),
  caterpie: require("../../assets/img/pokemons/caterpie.png"),
  metapod: require("../../assets/img/pokemons/metapod.png"),
  butterfree: require("../../assets/img/pokemons/butterfree.png"),
  weedle: require("../../assets/img/pokemons/weedle.png"),
  kakuna: require("../../assets/img/pokemons/kakuna.png"),
  beedrill: require("../../assets/img/pokemons/beedrill.png"),
  pidgey: require("../../assets/img/pokemons/pidgey.png"),
  pidgeotto: require("../../assets/img/pokemons/pidgeotto.png"),
  pidgeot: require("../../assets/img/pokemons/pidgeot.png"),
  rattata: require("../../assets/img/pokemons/rattata.png"),
  raticate: require("../../assets/img/pokemons/raticate.png")
};

export const POKE_SERVER_IMGS: Record<string, any> = {
  bulbasaur: "https://i.postimg.cc/SXZ1JJny/bulbasaur.png",
  ivysaur: "https://i.postimg.cc/3yLfddky/ivysaur.png",
  venusaur: "https://i.postimg.cc/qhzbn4Kt/venusaur.png",
  charmander: "https://i.postimg.cc/gwMtnnxx/charmander.png",
  charmeleon: "https://i.postimg.cc/f3HqJJVy/charmeleon.png",
  charizard: "https://i.postimg.cc/SXZ1JJnj/charizard.png",
  squirtle: "https://i.postimg.cc/mztXMB9P/squirtle.png",
  wartortle: "https://i.postimg.cc/dkLHdwCk/wartortle.png",
  blastoise: "https://i.postimg.cc/t1rvYYsq/blastoise.png",
  caterpie: "https://i.postimg.cc/sBnHvvMf/caterpie.png",
  metapod: "https://i.postimg.cc/WD9YhhdJ/metapod.png",
  butterfree: "https://i.postimg.cc/B8h7XXjJ/butterfree.png",
  weedle: "https://i.postimg.cc/LYnCf2Pg/weedle.png",
  kakuna: "https://i.postimg.cc/yJfpkkD3/kakuna.png",
  beedrill: "https://i.postimg.cc/PL6VPPCn/beedrill.png",
  pidgey: "https://i.postimg.cc/ZBC734N5/pidgey.png",
  pidgeotto: "https://i.postimg.cc/B8h7XXjD/pidgeotto.png",
  pidgeot: "https://i.postimg.cc/7CBtff52/pidgeot.png",
  rattata: "https://i.postimg.cc/JDG6JMXt/rattata.png",
  raticate: "https://i.postimg.cc/5Y67vbz0/raticate.png",
};
